"""add storage path to team files

Revision ID: 58879c1621e3
Revises: d95905b9f176
Create Date: 2026-04-28 22:07:28.695347

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58879c1621e3'
down_revision: Union[str, Sequence[str], None] = 'd95905b9f176'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team_files', sa.Column('storage_path', sa.String(), nullable=False))
    op.alter_column('team_files', 'file_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('team_files', 'file_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('team_files', 'storage_path')
    # ### end Alembic commands ###
