"""add extra team fields

Revision ID: 69ca225a102f
Revises: 
Create Date: 2026-04-23 20:29:27.354732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '69ca225a102f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teams', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('teams', sa.Column('conditions_to_join', sa.JSON(), nullable=True))
    op.add_column('teams', sa.Column('communication_method', sa.String(length=100), nullable=True))
    op.add_column('teams', sa.Column('meeting_frequency', sa.String(length=100), nullable=True))
    op.add_column('teams', sa.Column('timezone', sa.String(length=100), nullable=True))
    op.add_column('teams', sa.Column('collaboration_method', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('teams', 'collaboration_method')
    op.drop_column('teams', 'timezone')
    op.drop_column('teams', 'meeting_frequency')
    op.drop_column('teams', 'communication_method')
    op.drop_column('teams', 'conditions_to_join')
    op.drop_column('teams', 'category')
    # ### end Alembic commands ###
