"""add team workspace features

Revision ID: d95905b9f176
Revises: efed1f690857
Create Date: 2026-04-28 21:47:27.447628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd95905b9f176'
down_revision: Union[str, Sequence[str], None] = 'efed1f690857'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=True),
    sa.Column('file_type', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_files_id'), 'team_files', ['id'], unique=False)
    op.create_index(op.f('ix_team_files_team_id'), 'team_files', ['team_id'], unique=False)
    op.create_table('team_goals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(), nullable=False),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_goals_id'), 'team_goals', ['id'], unique=False)
    op.create_index(op.f('ix_team_goals_team_id'), 'team_goals', ['team_id'], unique=False)
    op.create_table('team_schedule_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('date_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_schedule_events_id'), 'team_schedule_events', ['id'], unique=False)
    op.create_index(op.f('ix_team_schedule_events_team_id'), 'team_schedule_events', ['team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_team_schedule_events_team_id'), table_name='team_schedule_events')
    op.drop_index(op.f('ix_team_schedule_events_id'), table_name='team_schedule_events')
    op.drop_table('team_schedule_events')
    op.drop_index(op.f('ix_team_goals_team_id'), table_name='team_goals')
    op.drop_index(op.f('ix_team_goals_id'), table_name='team_goals')
    op.drop_table('team_goals')
    op.drop_index(op.f('ix_team_files_team_id'), table_name='team_files')
    op.drop_index(op.f('ix_team_files_id'), table_name='team_files')
    op.drop_table('team_files')
    # ### end Alembic commands ###
